version: '3.8'

services:
  devaic:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: devaic-analyzer
    volumes:
      - ./code:/app/code:ro
      - ./reports:/app/reports
      - ./rules/custom:/app/rules:ro
    environment:
      - DEVAIC_OUTPUT_DIR=/app/reports
      - DEVAIC_CUSTOM_RULES_PATH=/app/rules
      - DEVAIC_LOG_LEVEL=info
    command: ["/app/code", "--compliance", "owasp", "--visualize", "--output-dir", "/app/reports"]
    
  devaic-lsp:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: devaic-lsp-server
    ports:
      - "9257:9257"
    environment:
      - DEVAIC_LSP_PORT=9257
    command: ["--lsp-server"]
    
  devaic-web:
    image: nginx:alpine
    container_name: devaic-web-dashboard
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - devaic